// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ST_BE.Data;

#nullable disable

namespace ST_BE.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20261003113135_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ST_BE.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bút & Dụng cụ viết",
                            Description = "Bút bi, bút chì, bút gel, bút dạ"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Giấy & Sổ",
                            Description = "Giấy in, giấy note, sổ tay, tập vở"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Dụng cụ học tập",
                            Description = "Thước, compa, tẩy, gọt bút chì"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Dụng cụ văn phòng",
                            Description = "Kéo, bấm kim, kẹp giấy, dao rọc giấy"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Lưu trữ & Hồ sơ",
                            Description = "Bìa hồ sơ, file tài liệu, hộp đựng hồ sơ"
                        });
                });

            modelBuilder.Entity("ST_BE.Models.Customers", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 4,
                            CustomerName = "Phạm Thị D",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0905234167",
                            RewardPoints = 200
                        },
                        new
                        {
                            CustomerId = 5,
                            CustomerName = "Hoàng Văn E",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0916342789",
                            RewardPoints = 80
                        },
                        new
                        {
                            CustomerId = 6,
                            CustomerName = "Võ Thị F",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0987456123",
                            RewardPoints = 25
                        },
                        new
                        {
                            CustomerId = 7,
                            CustomerName = "Đặng Văn G",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0908765432",
                            RewardPoints = 175
                        },
                        new
                        {
                            CustomerId = 8,
                            CustomerName = "Bùi Thị H",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 65
                        },
                        new
                        {
                            CustomerId = 9,
                            CustomerName = "Đỗ Văn I",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0987654321",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 10,
                            CustomerName = "Ngô Thị K",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0903456789",
                            RewardPoints = 250
                        },
                        new
                        {
                            CustomerId = 11,
                            CustomerName = "Phan Văn L",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0914567890",
                            RewardPoints = 95
                        },
                        new
                        {
                            CustomerId = 12,
                            CustomerName = "Huỳnh Thị M",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0981234567",
                            RewardPoints = 30
                        },
                        new
                        {
                            CustomerId = 13,
                            CustomerName = "Trương Văn N",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0909876543",
                            RewardPoints = 320
                        },
                        new
                        {
                            CustomerId = 14,
                            CustomerName = "Lý Thị O",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0917654321",
                            RewardPoints = 70
                        },
                        new
                        {
                            CustomerId = 15,
                            CustomerName = "Mai Văn P",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0984561230",
                            RewardPoints = 20
                        },
                        new
                        {
                            CustomerId = 16,
                            CustomerName = "Nguyễn Thị Q",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901234567",
                            RewardPoints = 180
                        },
                        new
                        {
                            CustomerId = 17,
                            CustomerName = "Trần Văn R",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912348901",
                            RewardPoints = 85
                        },
                        new
                        {
                            CustomerId = 18,
                            CustomerName = "Lê Thị S",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983456781",
                            RewardPoints = 35
                        },
                        new
                        {
                            CustomerId = 19,
                            CustomerName = "Phạm Văn T",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0904567891",
                            RewardPoints = 220
                        },
                        new
                        {
                            CustomerId = 20,
                            CustomerName = "Hoàng Thị U",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0915678902",
                            RewardPoints = 60
                        },
                        new
                        {
                            CustomerId = 21,
                            CustomerName = "Võ Văn V",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0986789012",
                            RewardPoints = 18
                        },
                        new
                        {
                            CustomerId = 22,
                            CustomerName = "Đặng Thị X",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0907890123",
                            RewardPoints = 275
                        },
                        new
                        {
                            CustomerId = 23,
                            CustomerName = "Bùi Văn Y",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918901234",
                            RewardPoints = 110
                        },
                        new
                        {
                            CustomerId = 24,
                            CustomerName = "Đỗ Thị Z",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0989012345",
                            RewardPoints = 40
                        },
                        new
                        {
                            CustomerId = 25,
                            CustomerName = "Nguyễn Văn Hùng",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0902345678",
                            RewardPoints = 350
                        },
                        new
                        {
                            CustomerId = 26,
                            CustomerName = "Trần Thị Lan",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0913456789",
                            RewardPoints = 75
                        },
                        new
                        {
                            CustomerId = 27,
                            CustomerName = "Lê Văn Minh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0984567891",
                            RewardPoints = 22
                        },
                        new
                        {
                            CustomerId = 28,
                            CustomerName = "Phạm Thị Hoa",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0905678901",
                            RewardPoints = 190
                        },
                        new
                        {
                            CustomerId = 29,
                            CustomerName = "Hoàng Văn Nam",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0916789012",
                            RewardPoints = 90
                        },
                        new
                        {
                            CustomerId = 30,
                            CustomerName = "Võ Thị Mai",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0987890123",
                            RewardPoints = 28
                        },
                        new
                        {
                            CustomerId = 31,
                            CustomerName = "Đặng Văn Sơn",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0908901234",
                            RewardPoints = 240
                        },
                        new
                        {
                            CustomerId = 32,
                            CustomerName = "Bùi Thị Ngọc",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0919012345",
                            RewardPoints = 100
                        },
                        new
                        {
                            CustomerId = 33,
                            CustomerName = "Đỗ Văn Thành",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0980123456",
                            RewardPoints = 12
                        },
                        new
                        {
                            CustomerId = 34,
                            CustomerName = "Nguyễn Thị Hương",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901237890",
                            RewardPoints = 310
                        },
                        new
                        {
                            CustomerId = 35,
                            CustomerName = "Trần Văn Bình",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912348902",
                            RewardPoints = 120
                        },
                        new
                        {
                            CustomerId = 36,
                            CustomerName = "Lê Thị Thảo",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983459012",
                            RewardPoints = 45
                        },
                        new
                        {
                            CustomerId = 37,
                            CustomerName = "Phạm Văn Long",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0904560123",
                            RewardPoints = 280
                        },
                        new
                        {
                            CustomerId = 38,
                            CustomerName = "Hoàng Thị Vân",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0915671234",
                            RewardPoints = 55
                        },
                        new
                        {
                            CustomerId = 39,
                            CustomerName = "Võ Văn Đức",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0986782345",
                            RewardPoints = 32
                        },
                        new
                        {
                            CustomerId = 40,
                            CustomerName = "Đặng Thị Nga",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0907893456",
                            RewardPoints = 365
                        },
                        new
                        {
                            CustomerId = 41,
                            CustomerName = "Bùi Văn Phúc",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918904567",
                            RewardPoints = 130
                        },
                        new
                        {
                            CustomerId = 42,
                            CustomerName = "Đỗ Thị Yến",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0989015678",
                            RewardPoints = 16
                        },
                        new
                        {
                            CustomerId = 43,
                            CustomerName = "Nguyễn Văn Khoa",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0902346789",
                            RewardPoints = 210
                        },
                        new
                        {
                            CustomerId = 44,
                            CustomerName = "Trần Thị Nhung",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0913457890",
                            RewardPoints = 105
                        },
                        new
                        {
                            CustomerId = 45,
                            CustomerName = "Lê Văn Dũng",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0984568901",
                            RewardPoints = 38
                        });
                });

            modelBuilder.Entity("ST_BE.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8938501234001",
                            CategoryId = 1,
                            Price = 5000m,
                            ProductName = "Bút bi Thiên Long TL-027",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8938501234002",
                            CategoryId = 1,
                            Price = 12000m,
                            ProductName = "Bút gel Thiên Long GEL-08",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8938501234003",
                            CategoryId = 1,
                            Price = 4000m,
                            ProductName = "Bút chì gỗ 2B",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8938501234004",
                            CategoryId = 1,
                            Price = 10000m,
                            ProductName = "Bút dạ quang vàng",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8938501234005",
                            CategoryId = 1,
                            Price = 15000m,
                            ProductName = "Bút lông dầu màu đen",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8938501234006",
                            CategoryId = 1,
                            Price = 25000m,
                            ProductName = "Bút máy học sinh",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8938501234007",
                            CategoryId = 1,
                            Price = 3000m,
                            ProductName = "Ruột bút bi xanh",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8938501234008",
                            CategoryId = 1,
                            Price = 12000m,
                            ProductName = "Bút marker xanh",
                            StockQuantity = 65
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8938501234009",
                            CategoryId = 1,
                            Price = 18000m,
                            ProductName = "Bút chì kim 0.5mm",
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8938501234010",
                            CategoryId = 2,
                            Price = 75000m,
                            ProductName = "Giấy A4 Double A 70gsm",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8938501234011",
                            CategoryId = 2,
                            Price = 15000m,
                            ProductName = "Giấy note 3x3 màu vàng",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8938501234012",
                            CategoryId = 2,
                            Price = 35000m,
                            ProductName = "Sổ tay lò xo A5",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8938501234013",
                            CategoryId = 2,
                            Price = 45000m,
                            ProductName = "Giấy A5 trắng 70gsm",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8938501234014",
                            CategoryId = 2,
                            Price = 55000m,
                            ProductName = "Sổ tay bìa cứng A5",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8938501234015",
                            CategoryId = 2,
                            Price = 22000m,
                            ProductName = "Tập vở 200 trang",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 16,
                            Barcode = "8938501234016",
                            CategoryId = 2,
                            Price = 65000m,
                            ProductName = "Giấy in màu A4",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "8938501234017",
                            CategoryId = 2,
                            Price = 48000m,
                            ProductName = "Sổ lò xo A4",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 18,
                            Barcode = "8938501234018",
                            CategoryId = 2,
                            Price = 20000m,
                            ProductName = "Giấy note nhiều màu",
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 19,
                            Barcode = "8938501234019",
                            CategoryId = 3,
                            Price = 7000m,
                            ProductName = "Thước kẻ 20cm",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 20,
                            Barcode = "8938501234020",
                            CategoryId = 3,
                            Price = 25000m,
                            ProductName = "Compa học sinh",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 21,
                            Barcode = "8938501234021",
                            CategoryId = 3,
                            Price = 5000m,
                            ProductName = "Tẩy chì trắng Thiên Long",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 22,
                            Barcode = "8938501234022",
                            CategoryId = 3,
                            Price = 8000m,
                            ProductName = "Gọt bút chì 2 lỗ",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 23,
                            Barcode = "8938501234023",
                            CategoryId = 3,
                            Price = 12000m,
                            ProductName = "Thước tam giác 20cm",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 24,
                            Barcode = "8938501234024",
                            CategoryId = 3,
                            Price = 30000m,
                            ProductName = "Bộ thước học sinh",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 25,
                            Barcode = "8938501234025",
                            CategoryId = 3,
                            Price = 35000m,
                            ProductName = "Hộp bút học sinh",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 26,
                            Barcode = "8938501234026",
                            CategoryId = 3,
                            Price = 28000m,
                            ProductName = "Màu sáp 12 màu",
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 27,
                            Barcode = "8938501234027",
                            CategoryId = 3,
                            Price = 40000m,
                            ProductName = "Bộ bút màu 12 màu",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 28,
                            Barcode = "8938501234028",
                            CategoryId = 4,
                            Price = 20000m,
                            ProductName = "Kéo văn phòng 18cm",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 29,
                            Barcode = "8938501234029",
                            CategoryId = 4,
                            Price = 30000m,
                            ProductName = "Bấm kim số 10",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 30,
                            Barcode = "8938501234030",
                            CategoryId = 4,
                            Price = 18000m,
                            ProductName = "Hộp kẹp giấy 100 cái",
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 31,
                            Barcode = "8938501234031",
                            CategoryId = 4,
                            Price = 15000m,
                            ProductName = "Dao rọc giấy nhỏ",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 32,
                            Barcode = "8938501234032",
                            CategoryId = 4,
                            Price = 10000m,
                            ProductName = "Băng keo trong 2cm",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 33,
                            Barcode = "8938501234033",
                            CategoryId = 4,
                            Price = 12000m,
                            ProductName = "Keo dán giấy",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 34,
                            Barcode = "8938501234034",
                            CategoryId = 4,
                            Price = 8000m,
                            ProductName = "Ghim bấm số 10",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 35,
                            Barcode = "8938501234035",
                            CategoryId = 4,
                            Price = 15000m,
                            ProductName = "Kẹp bướm 32mm",
                            StockQuantity = 65
                        },
                        new
                        {
                            ProductId = 36,
                            Barcode = "8938501234036",
                            CategoryId = 4,
                            Price = 22000m,
                            ProductName = "Bộ ghim giấy văn phòng",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 37,
                            Barcode = "8938501234037",
                            CategoryId = 5,
                            Price = 8000m,
                            ProductName = "Bìa hồ sơ A4 nút bấm",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 38,
                            Barcode = "8938501234038",
                            CategoryId = 5,
                            Price = 25000m,
                            ProductName = "File tài liệu A4 20 lá",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 39,
                            Barcode = "8938501234039",
                            CategoryId = 5,
                            Price = 45000m,
                            ProductName = "Hộp đựng hồ sơ A4",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 40,
                            Barcode = "8938501234040",
                            CategoryId = 5,
                            Price = 35000m,
                            ProductName = "Bìa còng A4",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 41,
                            Barcode = "8938501234041",
                            CategoryId = 5,
                            Price = 40000m,
                            ProductName = "File lá A4 40 lá",
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 42,
                            Barcode = "8938501234042",
                            CategoryId = 5,
                            Price = 30000m,
                            ProductName = "Bìa trình ký A4",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 43,
                            Barcode = "8938501234043",
                            CategoryId = 5,
                            Price = 7000m,
                            ProductName = "Túi hồ sơ A4",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 44,
                            Barcode = "8938501234044",
                            CategoryId = 5,
                            Price = 55000m,
                            ProductName = "Hộp lưu trữ tài liệu",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 45,
                            Barcode = "8938501234045",
                            CategoryId = 5,
                            Price = 10000m,
                            ProductName = "Bìa hồ sơ có dây",
                            StockQuantity = 75
                        });
                });

            modelBuilder.Entity("ST_BE.Models.Product", b =>
                {
                    b.HasOne("ST_BE.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ST_BE.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
