// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ST_BE.Data;

#nullable disable

namespace ST_BE.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20261003112421_add")]
    partial class add
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ST_BE.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bút & Dụng cụ viết",
                            Description = "Bút bi, bút chì, bút gel, bút dạ"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Giấy & Sổ",
                            Description = "Giấy in, giấy note, sổ tay, tập vở"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Dụng cụ học tập",
                            Description = "Thước, compa, tẩy, gọt bút chì"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Dụng cụ văn phòng",
                            Description = "Kéo, bấm kim, kẹp giấy, dao rọc giấy"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Lưu trữ & Hồ sơ",
                            Description = "Bìa hồ sơ, file tài liệu, hộp đựng hồ sơ"
                        });
                });

            modelBuilder.Entity("ST_BE.Models.Customers", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 4,
                            CustomerName = "Phạm Thị D",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0905234167",
                            RewardPoints = 200
                        },
                        new
                        {
                            CustomerId = 5,
                            CustomerName = "Hoàng Văn E",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0916342789",
                            RewardPoints = 80
                        },
                        new
                        {
                            CustomerId = 6,
                            CustomerName = "Võ Thị F",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0987456123",
                            RewardPoints = 25
                        },
                        new
                        {
                            CustomerId = 7,
                            CustomerName = "Đặng Văn G",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0908765432",
                            RewardPoints = 175
                        },
                        new
                        {
                            CustomerId = 8,
                            CustomerName = "Bùi Thị H",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 65
                        },
                        new
                        {
                            CustomerId = 9,
                            CustomerName = "Đỗ Văn I",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0987654321",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 10,
                            CustomerName = "Ngô Thị K",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0903456789",
                            RewardPoints = 250
                        },
                        new
                        {
                            CustomerId = 11,
                            CustomerName = "Phan Văn L",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0914567890",
                            RewardPoints = 95
                        },
                        new
                        {
                            CustomerId = 12,
                            CustomerName = "Huỳnh Thị M",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0981234567",
                            RewardPoints = 30
                        },
                        new
                        {
                            CustomerId = 13,
                            CustomerName = "Trương Văn N",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0909876543",
                            RewardPoints = 320
                        },
                        new
                        {
                            CustomerId = 14,
                            CustomerName = "Lý Thị O",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0917654321",
                            RewardPoints = 70
                        },
                        new
                        {
                            CustomerId = 15,
                            CustomerName = "Mai Văn P",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0984561230",
                            RewardPoints = 20
                        });
                });

            modelBuilder.Entity("ST_BE.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8938501234001",
                            CategoryId = 1,
                            Price = 5000m,
                            ProductName = "Bút bi Thiên Long TL-027",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8938501234002",
                            CategoryId = 1,
                            Price = 12000m,
                            ProductName = "Bút gel Thiên Long GEL-08",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8938501234003",
                            CategoryId = 1,
                            Price = 4000m,
                            ProductName = "Bút chì gỗ 2B",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8938501234004",
                            CategoryId = 2,
                            Price = 75000m,
                            ProductName = "Giấy A4 Double A 70gsm",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8938501234005",
                            CategoryId = 2,
                            Price = 15000m,
                            ProductName = "Giấy note 3x3 màu vàng",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8938501234006",
                            CategoryId = 2,
                            Price = 35000m,
                            ProductName = "Sổ tay lò xo A5",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8938501234007",
                            CategoryId = 3,
                            Price = 7000m,
                            ProductName = "Thước kẻ 20cm",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8938501234008",
                            CategoryId = 3,
                            Price = 25000m,
                            ProductName = "Compa học sinh",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8938501234009",
                            CategoryId = 3,
                            Price = 5000m,
                            ProductName = "Tẩy chì trắng Thiên Long",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8938501234010",
                            CategoryId = 4,
                            Price = 20000m,
                            ProductName = "Kéo văn phòng 18cm",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8938501234011",
                            CategoryId = 4,
                            Price = 30000m,
                            ProductName = "Bấm kim số 10",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8938501234012",
                            CategoryId = 4,
                            Price = 18000m,
                            ProductName = "Hộp kẹp giấy 100 cái",
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8938501234013",
                            CategoryId = 5,
                            Price = 8000m,
                            ProductName = "Bìa hồ sơ A4 nút bấm",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8938501234014",
                            CategoryId = 5,
                            Price = 25000m,
                            ProductName = "File tài liệu A4 20 lá",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8938501234015",
                            CategoryId = 5,
                            Price = 45000m,
                            ProductName = "Hộp đựng hồ sơ A4",
                            StockQuantity = 30
                        });
                });

            modelBuilder.Entity("ST_BE.Models.Product", b =>
                {
                    b.HasOne("ST_BE.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ST_BE.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
